name: my_first_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.5
  cupertino_icons: ^1.0.8
  video_player: ^2.5.1
  flutter_local_notifications: ^18.0.1
  vibration: ^2.0.1
  device_info_plus: ^11.2.1
  permission_handler: ^11.3.1
  flutter_riverpod: ^2.6.1
  web_socket_channel: ^3.0.2
  image_picker: ^1.1.2
  flutter_vlc_player: ^7.4.2
  sensors_plus: ^6.1.1
  dio: ^5.8.0+1
  flutter_localization: ^0.3.2
  intl: ^0.19.0
  fl_chart: ^0.70.2
  url_launcher: ^6.3.1
  crypto: ^3.0.6
  webview_flutter: ^4.10.0
  flutter_launcher_icons: ^0.14.3
  just_audio: ^0.10.2
  flutter_speed_dial: ^7.0.0
  file_picker: ^10.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  intl_utils: ^2.8.10


flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/assets/videos/
    - lib/assets/images/
    - lib/assets/icons/
    - lib/assets/audios/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/icons/app_icon.png"
  remove_alpha_ios: true
